sudo: required
dist: focal

services:
- docker

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y bzip2
- while sleep 5m; do echo "=====[ $SECONDS seconds, still building... ]====="; done &
- mkdir -vp ~/.docker/cli-plugins/
- if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then
  curl --silent -L "https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-arm64" > ~/.docker/cli-plugins/docker-buildx
  else
  curl --silent -L "https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  fi
- chmod a+x ~/.docker/cli-plugins/docker-buildx

script:
- docker buildx version
- export DOCKER_CLI_EXPERIMENTAL=enabled
- bash init.sh
- docker buildx create --use --name mybuild
- docker buildx build --platform linux/amd64,linux/arm64 -t wise2c/playbook:$TRAVIS_BRANCH .

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push wise2c/playbook:$TRAVIS_BRANCH
  on:
    all_branches: true
#    condition: "$TRAVIS_BRANCH =~ ^v[0-9]+\\.[0-9]+(\\.[0-9]+)?(-\\S*)?$"
